/* 1 */
libname FORMA "/ker7/Qsasgrp/FormationSasLangage";
libname PERSO "/deci/Zsasgrp/VGD_Grp/FormationSasLangage";

/* 2 */
data PERSO.TAWICTR_EXTRACT ;
set FORMA.TAWICTR (
	firstobs=10000 obs=160000
	keep=AWICTR_CLEPAR AWICTR_CODPRD AWICTR_NUMCTR AWICTR_CODANM AWICTR_NUMASR
		 AWICTR_NUMTIE AWICTR_CODBCH AWICTR_CODSPD AWICTR_DATSAICTR AWICTR_CTSANNHT
		AWICTR_CMRCTX AWICTR_FLGFRTPTR AWICTR_FLGFNCPTR AWICTR_FLGCRTPTR AWICTR_FLGIPYPTR 
		AWICTR_FLGELIFRT AWICTR_USRSASSOU
	);
run;

/* 3 */
data PERSO.REFERENTIEL_BRANCHES ;
	length CODE_BRANCHE $2 LIBELLE_BRANCHE $15;
	infile datalines delimiter="-";
    input CODE_BRANCHE  $ LIBELLE_BRANCHE $ ;
    datalines;
01-AUTOMOBILE
02-IARD ET P.J.
03-PREV. SANTE
04-PREV. DECES
05-CREDITS
06-COURTAGE
07-BON DE CAPI
08-PRIME UNIQUE
09-LIVRET
12-CAUTION
;
run;

/* 4 */
proc sort data=PERSO.TAWICTR_EXTRACT ;
	by AWICTR_CODBCH;
run;

data PERSO.FUSION_TAWICTR_BRANCHE ;
	merge PERSO.TAWICTR_EXTRACT (in=a)
 	  	  PERSO.REFERENTIEL_BRANCHES (in=b rename=(CODE_BRANCHE=AWICTR_CODBCH));
	by AWICTR_CODBCH;
	label MOIS_SAISIE="Mois de saisie";
	FIN_NUMTIE=substr(AWICTR_NUMTIE,length(AWICTR_NUMTIE)-1,2);
	MOIS_SAISIE=month(AWICTR_DATSAICTR);
run;

/* 5 */
proc freq data=PERSO.FUSION_TAWICTR_BRANCHE;
	tables LIBELLE_BRANCHE*AWICTR_CLEPAR;
run;

/* 6 */
proc sort data=PERSO.FUSION_TAWICTR_BRANCHE;
	by LIBELLE_BRANCHE;
run;
proc means data=PERSO.FUSION_TAWICTR_BRANCHE;
	var AWICTR_CTSANNHT;
	by LIBELLE_BRANCHE;
run;


